spring:
  profiles:
    active: production
  application:
    name: example-api

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile: production

k8s:
  podName: ${POD_NAME}
  nodeName: ${NODE_NAME}

---
spring:
  config:
    activate:
      on-profile: test
  liquibase:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    user: sa
    password: sa
  r2dbc:
    url: r2dbc:h2:mem:///db?options=DB_CLOSE_DELAY=-1
    username: sa
    password: sa

k8s:
  podName: 'test-pod-name'
  nodeName: 'test-node-name'

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    url: jdbc://postgresql://localhost:5432/example_api
    user: test
    password: test
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example_api
    username: test
    password: test

k8s:
  podName: 'test-pod-name'
  nodeName: 'test-node-name'
